<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;

// Autogenerated routes for authentification.
Auth::routes();

Route::get('/home', function () {
    return redirect('/');
});

// Ensure that these routes are only accessible for loggedin users.
Route::group(['middleware' => 'auth'], function () {

    Route::get('/', 'TodoController@index')->name('todos');

    Route::post('/todo', 'TodoController@create');

    // These routes should preferably be implemented as PUT and DELETE request instead.
    Route::get('/todo/{id}/complete', 'TodoController@toggleComplete');
    Route::get('/delete', 'TodoController@deleteCompleted');
});
